# Generated by Django 4.2.8 on 2023-12-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
